CREATE DATABASE Q1
USE Q1
CREATE TABLE Scientist (
	SID INT PRIMARY KEY,
	COUNTRY VARCHAR(50),
	SNam VARCHAR(50),
	FName VARCHAR(50),
	LName VARCHAR(50)
);
GO
CREATE TABLE RArea(
	SID INT PRIMARY KEY,
	RArea VARCHAR(50),
	CONSTRAINT [FK_RArea_Scientist] FOREIGN KEY (SID) REFERENCES Scientist(SID)
);
GO
CREATE TABLE Invention(
	IID INT PRIMARY KEY,
	IName VARCHAR(50),
	[Year] INT
);
GO
CREATE TABLE Invents(
	SID INT,
	IID INT,
	PRIMARY KEY (SID, IID),
	CONSTRAINT [FK_Invents_Scientist] FOREIGN KEY (SID) REFERENCES Scientist(SID),
	CONSTRAINT [FK_Invents_Invention] FOREIGN KEY (IID) REFERENCES Invention(IID)
);