select * from GIAOVIEN;

SELECT MAGV, HOTEN
FROM GIAOVIEN;

SELECT DISTINCT HOCHAM
FROM GIAOVIEN;

SELECT COUNT(DISTINCT HOCHAM)
AS SOLUONG
FROM GIAOVIEN;

SELECT COUNT(HOCHAM)
AS SOLUONG
FROM GIAOVIEN;

SELECT COUNT(DISTINCT MAGV)
AS SOLUONG_GV
FROM GIAOVIEN;

SELECT HOTEN
FROM GIAOVIEN
WHERE MAGV = 'GV01'

SELECT HOTEN,HOCVI, GIOITINH
FROM GIAOVIEN
WHERE HESO <= 3

SELECT HOTEN,HOCVI, GIOITINH
FROM GIAOVIEN
WHERE GIOITINH <> 'Nam'

SELECT HOTEN,HOCVI, GIOITINH
FROM GIAOVIEN
WHERE HESO BETWEEN 3 AND 5

SELECT * FROM GIAOVIEN
WHERE HOTEN LIKE '%ANH'

SELECT * FROM GIAOVIEN
WHERE HOTEN LIKE '%SON'

SELECT * FROM GIAOVIEN
WHERE HOCVI LIKE 'P_S'

SELECT * FROM GIAOVIEN
ORDER BY HOTEN ASC

SELECT * FROM GIAOVIEN
ORDER BY HOTEN, MUCLUONG DESC

SELECT * FROM GIAOVIEN
ORDER BY HESO ASC, MUCLUONG DESC

SELECT * FROM GIAOVIEN
WHERE HOCVI = 'THS' AND HESO > 3

SELECT * FROM GIAOVIEN
WHERE HOCVI = 'THS' OR HESO > 3

SELECT * FROM GIAOVIEN
WHERE NOT HOCVI = 'TS'

INSERT INTO GIAOVIEN(MAGV, HOTEN)
VALUES ('GV18','BRAVEE06')

SELECT * FROM GIAOVIEN